# https://www.mkdocs.org

# Project
site_name: django-user-trace
site_author: Jonathan Hiles
site_description: A Python logging filter for Django user attributes

# Copyright
copyright: Copyright &copy; 2023 Jonathan Hiles

# Repository
repo_name: axieum/django-user-trace
repo_url: https://github.com/axieum/django-user-trace

# Theme
theme:
  name: material
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow
  icon:
    edit: octicons/file-code-24
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Customisation
extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/django-user-trace
    - icon: fontawesome/brands/github
      link: https://github.com/axieum
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jonathan-hiles
    - icon: fontawesome/solid/envelope
      link: mailto:jonathan@hil.es
      name: jonathan@hil.es
  version:
    provider: mike

# Watch
watch:
  - CHANGELOG.md
  - CONTRIBUTING.md
  - README.md
  - SECURITY.md

# Plugins
plugins:
  - awesome-pages:
      filename: .pages.yml
  - gen-files:
      scripts:
        - docs/changelog/index.py
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: timeago
  - minify:
      minify_html: true
  - search

# Markdown
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: '#'
